server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/lovable-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    
  ai:
    model.chat: openai
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
          # model: google/gemini-3-flash-preview
          model: stepfun/step-3.5-flash:free
          temperature: 0.2
      embedding:
        options:
          model: qwen/qwen3-embedding-8b
